"""Add centralized stat tracking

Revision ID: 3f14c1ace2c8
Revises: e5578cb41bcb
Create Date: 2025-10-24 22:45:26.454315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f14c1ace2c8'
down_revision = 'e5578cb41bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_games_played', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('daily_reward_streak', sa.Integer(), nullable=True))
        batch_op.alter_column('workouts_completed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('avatars_created',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('items_unlocked',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_activity_date')

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.alter_column('items_unlocked',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('avatars_created',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('workouts_completed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('daily_reward_streak')
        batch_op.drop_column('total_games_played')

    # ### end Alembic commands ###
