"""Initial migration

Revision ID: e5578cb41bcb
Revises: 
Create Date: 2025-10-24 20:05:02.057030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5578cb41bcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('xp_earned',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('played_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('unlocked_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_catalog_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unlock_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_equipped', sa.Boolean(), nullable=True))
        batch_op.alter_column('item_category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('item_value',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('avatar_style',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('achievement_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('target', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('unique_user_achievement'), type_='unique')
        batch_op.drop_column('achievement_id')
        batch_op.drop_column('earned_at')

    with op.batch_alter_table('user_game_stats', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workouts_completed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_activity_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_activity_date')
        batch_op.drop_column('workouts_completed')

    with op.batch_alter_table('user_game_stats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('achievement_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('unique_user_achievement'), ['user_id', 'achievement_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('completed_date')
        batch_op.drop_column('target')
        batch_op.drop_column('achievement_description')
        batch_op.drop_column('achievement_name')

    with op.batch_alter_table('unlocked_items', schema=None) as batch_op:
        batch_op.alter_column('avatar_style',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('item_value',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('item_category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('is_equipped')
        batch_op.drop_column('unlock_method')
        batch_op.drop_column('item_catalog_id')

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.alter_column('played_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('xp_earned',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('game_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
