"""empty message

Revision ID: eff762cf9ae7
Revises: 0763d677d453
Create Date: 2025-09-09 20:41:25.842624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff762cf9ae7'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avatar_style', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('avatar_seed', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('avatar_background_color', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('avatar_theme', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('avatar_mood', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_mood')
        batch_op.drop_column('avatar_theme')
        batch_op.drop_column('avatar_background_color')
        batch_op.drop_column('avatar_seed')
        batch_op.drop_column('avatar_style')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
